// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; // Contoh jika ada Header
import Footer from "@/components/Footer"; // Contoh jika ada Footer

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* 👇 Bungkus children dengan <main> dan tambahkan kelasnya di sini */}
        <main className="container mx-auto max-w-7xl px-4">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}