// import { type Product } from "./types"

// export const allProducts: Product[] = [
//   {
//     id: "1",
//     name: "Classic Leather Watch",
//     image: "https://placehold.co/400x400.png",
//     price: 150.0,
//     originalPrice: 200.0,
//     rating: 4,
//     reviews: 120,
//     onSale: true,
//     isNew: true,
//     category: "Accessories",
//   },
//   {
//     id: "2",
//     name: "Wireless Bluetooth Headphones",
//     image: "https://placehold.co/400x400.png",
//     price: 99.99,
//     rating: 5,
//     reviews: 350,
//     onSale: false,
//     isNew: true,
//     category: "Electronics",
//   },
//   {
//     id: "3",
//     name: "Minimalist Desk Lamp",
//     image: "https://placehold.co/400x400.png",
//     price: 45.5,
//     rating: 4,
//     reviews: 88,
//     onSale: false,
//     isNew: false,
//     category: "Home Goods",
//   },
//   {
//     id: "4",
//     name: "Organic Cotton T-Shirt",
//     image: "https://placehold.co/400x400.png",
//     price: 25.0,
//     rating: 5,
//     reviews: 450,
//     onSale: false,
//     isNew: false,
//     category: "Apparel",
//   },
//   {
//     id: "5",
//     name: "Stainless Steel Water Bottle",
//     image: "https://placehold.co/400x400.png",
//     price: 30.0,
//     originalPrice: 40.0,
//     rating: 4,
//     reviews: 210,
//     onSale: true,
//     isNew: false,
//     category: "Lifestyle",
//   },
//   {
//     id: "6",
//     name: "Smart Fitness Tracker",
//     image: "https://placehold.co/400x400.png",
//     price: 79.99,
//     rating: 4,
//     reviews: 180,
//     onSale: false,
//     isNew: true,
//     category: "Electronics",
//   },
//   {
//     id: "7",
//     name: "Gourmet Coffee Bean Blend",
//     image: "https://placehold.co/400x400.png",
//     price: 22.0,
//     rating: 5,
//     reviews: 500,
//     onSale: false,
//     isNew: false,
//     category: "Groceries",
//   },
//   {
//     id: "8",
//     name: "Handcrafted Leather Wallet",
//     image: "https://placehold.co/400x400.png",
//     price: 65.0,
//     originalPrice: 80.0,
//     rating: 5,
//     reviews: 95,
//     onSale: true,
//     isNew: false,
//     category: "Accessories",
//   },
//   {
//     id: "9",
//     name: "Portable Power Bank",
//     image: "https://placehold.co/400x400.png",
//     price: 49.99,
//     rating: 4,
//     reviews: 250,
//     onSale: false,
//     isNew: true,
//     category: "Electronics",
//   },
//   {
//     id: "10",
//     name: "Scented Soy Wax Candle",
//     image: "https://placehold.co/400x400.png",
//     price: 18.0,
//     rating: 4,
//     reviews: 150,
//     onSale: false,
//     isNew: false,
//     category: "Home Goods",
//   },
//   {
//     id: "11",
//     name: "Stylish Canvas Backpack",
//     image: "https://placehold.co/400x400.png",
//     price: 85.0,
//     originalPrice: 110.0,
//     rating: 5,
//     reviews: 130,
//     onSale: true,
//     isNew: true,
//     category: "Bags",
//   },
//   {
//     id: "12",
//     name: "Ergonomic Office Chair",
//     image: "https://placehold.co/400x400.png",
//     price: 250.0,
//     originalPrice: 350.0,
//     rating: 5,
//     reviews: 75,
//     onSale: true,
//     isNew: false,
//     category: "Furniture",
//   },
// ]
